services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=patient_portal
      - MYSQL_USER=greg
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  express-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=greg
      - DB_PASSWORD=password
      - DB_NAME=patient_portal
    depends_on:
      mysql:
        condition: service_healthy
    command: nodemon --legacy-watch server.js
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: